CitasBufete/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasBufete.Data;
using CitasBufete.Models;

namespace CitasBufete.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _context.Cliente != null ? 
                          View(await _context.Cliente.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Cliente'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cliente == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre_completo,Identificacion,Medio_pago,Fecha_nacimiento")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                var s_cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Identificacion == cliente.Identificacion);
                if (s_cliente != null)
                {
                    ModelState.AddModelError(nameof(Cliente.Identificacion), "La identificación ingresada ya existe");
                    return View(cliente);
                }
                if (15>=GetYearsOld(cliente.Fecha_nacimiento))
                {
                    ModelState.AddModelError(nameof(Cliente.Fecha_nacimiento), "Debe ser mayor de 15 años para registrarse");
                    return View(cliente);
                }
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction("Login");
                
            }
            return View(cliente);
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string identificacion, DateTime fecha_nacimiento)
        {
            if (identificacion == null || fecha_nacimiento == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Identificacion == identificacion);
            if (cliente == null || cliente.Fecha_nacimiento != fecha_nacimiento)
            {
                ModelState.AddModelError(nameof(Cliente.Fecha_nacimiento), "Los datos de autenticación no son correctos");
                return View(cliente);
            }
            HttpContext.Session.SetInt32("Id_cliente", cliente.Id);
            HttpContext.Session.SetString("Nombre_cliente", cliente.Nombre_completo);
            var citas = from c in _context.Cita select c;
            citas = citas.Where(c => c.Id_cliente == cliente.Id).OrderByDescending(c => c.Fecha);
            return View("CitasCliente", citas);
        }

        public IActionResult CitasCliente()
        {
            var citas = from c in _context.Cita select c;
            citas = citas.Where(c => c.Id_cliente == (int)HttpContext.Session.GetInt32("Id_cliente"));
            return View("CitasCliente", citas);
            return View(citas);
        }

        public IActionResult Logout()
        {
           
            return  View();
        }

        [HttpPost, ActionName("Logout")]
        public IActionResult Logout(int? id)
        {
            if (HttpContext.Session.GetString("Nombre_cliente") != null)
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cliente == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre_completo,Identificacion,Medio_pago,Fecha_nacimiento")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cliente == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cliente == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cliente'  is null.");
            }
            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente != null)
            {
                _context.Cliente.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return (_context.Cliente?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public static int GetYearsOld(DateTime birthdate)
        {
            var diff = DateTime.Now - birthdate;
            return (int)(diff.TotalDays / 365.255);
        }
    }
}

CitasBufete/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CitasBufete</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasBufete.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CitasBufete</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (@Context.Session.GetString("Nombre_cliente") != null)
                        {
                           <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="CitasCliente">Gestionar Citas</a>
                            </li> 
                        }
                        else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Login">Autenticar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Create">Registrarse</a>
                            </li> 
                        }
                        
                    </ul>
                </div>
                @if (@Context.Session.GetString("Nombre_cliente") != null)
                {
                  <h5>@Context.Session.GetString("Nombre_cliente")</h5>  
                  <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Logout">Cerrar Sesion</a>
                }
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CitasBufete - Esteban Felipe Castillo Guillen <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>