CitasBufete/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;

namespace CitasBufete.Models
{
    public class Cliente
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage="Campo requerido")]
        [Display(Name="Nombre completo")]
        public string Nombre_completo { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Identificación")]
        public string Identificacion { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Medio de pago")]
        public string Medio_pago { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Fecha de  nacimiento")]
        [DataType(DataType.Date)]
        public DateTime Fecha_nacimiento { get; set; }

    }
}

CitasBufete/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasBufete.Data;
using CitasBufete.Models;

namespace CitasBufete.Controllers
{
    public class CitasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CitasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Citas
        public async Task<IActionResult> Index()
        {
              return _context.Cita != null ? 
                          View(await _context.Cita.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Cita'  is null.");
        }

        // GET: Citas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cita == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // GET: Citas/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("Id_cliente") != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Clientes");

        }

        // POST: Citas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha_solicitud,Id_cliente,Nombre_cliente,Especialidad,Fecha,Hora")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                if (new[] { DayOfWeek.Sunday, DayOfWeek.Saturday }.Contains(cita.Fecha.DayOfWeek))
                {
                    ModelState.AddModelError(nameof(Cita.Fecha), "Solo puede agendar citas de lunes a viernes");
                    return View(cita);
                }
                if ((DateTime.Now.Date.AddDays(1)) > cita.Fecha)
                {
                    ModelState.AddModelError(nameof(Cita.Fecha), "Solo puede agendar citas desde mañana y a más tardar 22 días después");
                    return View(cita);
                }
                if (22<CountDays(cita.Fecha))
                {
                    ModelState.AddModelError(nameof(Cita.Fecha), "Solo puede agendar citas desde el día siguiente y a más tardar 22 días después");
                    return View(cita);
                }
                var citas = from c in _context.Cita select c;
                citas = citas.Where(c => c.Fecha == cita.Fecha);
                foreach (var item in citas)
                {
                    if (item.Especialidad==cita.Especialidad && item.Hora == cita.Hora)
                    {
                        ModelState.AddModelError(nameof(Cita.Hora), "No existen espacios disponibles para esa especialidad a la hora seleccionada");
                        return View(cita);
                    }

                }
                citas = from c in _context.Cita select c;
                citas = citas.Where(c => c.Id_cliente == (int)HttpContext.Session.GetInt32("Id_cliente"));
                foreach (var item in citas)
                {
                    if (item.Especialidad == cita.Especialidad && item.Fecha > DateTime.Now.Date)
                    {
                        ModelState.AddModelError(nameof(Cita.Especialidad), "Ya cuenta con una cita para la especialidad seleccionada");
                        return View(cita);
                    }

                }

                cita.Fecha_solicitud = DateTime.Now.Date;
                cita.Id_cliente= (int)HttpContext.Session.GetInt32("Id_cliente");
                cita.Nombre_cliente= HttpContext.Session.GetString("Nombre_cliente");
                _context.Add(cita);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details",cita);
            }
            return View(cita);
            
        }

        // GET: Citas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cita == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita.FindAsync(id);
            if (cita == null)
            {
                return NotFound();
            }
            return View(cita);
        }

        // POST: Citas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha_solictud,Id_cliente,Nombre_cliente,Especialidad,Fecha,Hora")] Cita cita)
        {
            if (id != cita.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CitaExists(cita.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cita);
        }

        // GET: Citas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cita == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cita == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cita'  is null.");
            }
            var cita = await _context.Cita.FindAsync(id);
            if (cita != null)
            {
                _context.Cita.Remove(cita);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("CitasCliente","Clientes");
        }

        private bool CitaExists(int id)
        {
          return (_context.Cita?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public static int CountDays(DateTime enddate)
        {
            var diff =  enddate- DateTime.Now;
            return (int)diff.TotalDays; 
        }

         
        
    }
}

CitasBufete/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasBufete.Data;
using CitasBufete.Models;

namespace CitasBufete.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _context.Cliente != null ? 
                          View(await _context.Cliente.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Cliente'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cliente == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre_completo,Identificacion,Medio_pago,Fecha_nacimiento")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                var s_cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Identificacion == cliente.Identificacion);
                if (s_cliente != null)
                {
                    ModelState.AddModelError(nameof(Cliente.Identificacion), "La identificación ingresada ya existe");
                    return View(cliente);
                }
                if (15>=GetYearsOld(cliente.Fecha_nacimiento))
                {
                    ModelState.AddModelError(nameof(Cliente.Fecha_nacimiento), "Debe ser mayor de 15 años para registrarse");
                    return View(cliente);
                }
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction("Login");
                
            }
            return View(cliente);
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string identificacion, DateTime fecha_nacimiento)
        {
            if (identificacion == null || fecha_nacimiento == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Identificacion == identificacion);
            if (cliente == null || cliente.Fecha_nacimiento != fecha_nacimiento)
            {
                ModelState.AddModelError(nameof(Cliente.Fecha_nacimiento), "Los datos de autenticación no son correctos");
                return View(cliente);
            }
            HttpContext.Session.SetInt32("Id_cliente", cliente.Id);
            HttpContext.Session.SetString("Nombre_cliente", cliente.Nombre_completo);
            var citas = from c in _context.Cita select c;
            citas = citas.Where(c => c.Id_cliente == cliente.Id).OrderByDescending(c => c.Fecha);
            return View("CitasCliente", citas);
        }

        public IActionResult CitasCliente()
        {
            var citas = from c in _context.Cita select c;
            citas = citas.Where(c => c.Id_cliente == (int)HttpContext.Session.GetInt32("Id_cliente"));
            return View("CitasCliente", citas);
            return View(citas);
        }

        public IActionResult Logout()
        {
           
            return  View();
        }

        [HttpPost, ActionName("Logout")]
        public IActionResult Logout(int? id)
        {
            if (HttpContext.Session.GetString("Nombre_cliente") != null)
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cliente == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre_completo,Identificacion,Medio_pago,Fecha_nacimiento")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cliente == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cliente == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cliente'  is null.");
            }
            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente != null)
            {
                _context.Cliente.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return (_context.Cliente?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public static int GetYearsOld(DateTime birthdate)
        {
            var diff = DateTime.Now - birthdate;
            return (int)(diff.TotalDays / 365.255);
        }
    }
}

CitasBufete/Views/Clientes/CitasCliente.cshtml
@model IEnumerable<CitasBufete.Models.Cita>

@{
    ViewData["Title"] = "Gestionar Citas";
    var modelOrdered = Model.OrderByDescending(m=>m.Fecha); 
}

                                                               
   

<h1>Gestionar Citas</h1>

<p>
    <a class="btn btn-primary" asp-controller="Citas" asp-action="Create">Crear una nueva cita</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Estado
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_solicitud)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in modelOrdered) {
            <tr>
                <td>
                    @if (DateTime.Today < item.Fecha)
                    {
                        <p>Activa</p>
                    }
                    else
                    {
                        <p>Acudio</p>
                    }
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>            <td>
                @Html.DisplayFor(modelItem => item.Fecha_solicitud)
            </td>
            <td>
                @if (DateTime.Today < item.Fecha)
                    {
                        <a asp-controller="Citas" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a> 
                    }
                
            </td>
        </tr>
}
    </tbody>
</table>

CitasBufete/Views/Clientes/Create.cshtml
@model CitasBufete.Models.Cliente

@{
    ViewData["Title"] = "Registro de cliente";
}

<h1>Registro de cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre_completo" class="control-label"></label>
                <input asp-for="Nombre_completo" class="form-control" />
                <span asp-validation-for="Nombre_completo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Identificacion" class="control-label"></label>
                <input asp-for="Identificacion" class="form-control" />
                <span asp-validation-for="Identificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medio_pago" class="control-label"></label></br>
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>
                    {
                       new SelectListItem{ Text="Tarjeta", Value = "Tarjeta" },
                       new SelectListItem{ Text="Depósito", Value = "Depósito" },
                       new SelectListItem{ Text="SINPE Móvil", Value = "SINPE Móvil" },
                    };
                }

                @Html.DropDownListFor(model => model.Medio_pago, listItems, "Seleccione")
                <span asp-validation-for="Medio_pago" class="text-danger"></span>
            </div></br>
            <div class="form-group">
                <label asp-for="Fecha_nacimiento" class="control-label"></label>
                <input asp-for="Fecha_nacimiento" class="form-control" />
                <span asp-validation-for="Fecha_nacimiento" class="text-danger"></span>
            </div></br>
            <div class="form-group">
                <input type="submit" value="Registrarse" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div></br>

<div></br>
    <a asp-controller="Home" asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasBufete/Views/Clientes/Delete.cshtml
@model CitasBufete.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_completo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_completo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Identificacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Identificacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medio_pago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medio_pago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_nacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_nacimiento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CitasBufete/Views/Clientes/Details.cshtml
@model CitasBufete.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_completo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_completo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Identificacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Identificacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Medio_pago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Medio_pago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_nacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_nacimiento)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CitasBufete/Views/Clientes/Edit.cshtml
@model CitasBufete.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre_completo" class="control-label"></label>
                <input asp-for="Nombre_completo" class="form-control" />
                <span asp-validation-for="Nombre_completo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Identificacion" class="control-label"></label>
                <input asp-for="Identificacion" class="form-control" />
                <span asp-validation-for="Identificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Medio_pago" class="control-label"></label>
                <input asp-for="Medio_pago" class="form-control" />
                <span asp-validation-for="Medio_pago" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_nacimiento" class="control-label"></label>
                <input asp-for="Fecha_nacimiento" class="form-control" />
                <span asp-validation-for="Fecha_nacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasBufete/Views/Clientes/Index.cshtml
@model IEnumerable<CitasBufete.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_completo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Identificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medio_pago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_nacimiento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_completo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Identificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Medio_pago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_nacimiento)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CitasBufete/Views/Clientes/Login.cshtml
@model CitasBufete.Models.Cliente

@{
    ViewData["Title"] = "Login";
}

<h1>Autenticarse</h1>

<h5>Ingrese los datos</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div class="form-group">
                <label asp-for="Identificacion" class="control-label"></label>
                <input asp-for="Identificacion" class="form-control" />
                <span asp-validation-for="Identificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_nacimiento" class="control-label"></label>
                <input asp-for="Fecha_nacimiento" class="form-control" />
                <span asp-validation-for="Fecha_nacimiento" class="text-danger"></span>
            </div></br>
            <div class="form-group">
                <input type="submit" value="Iniciar sesión" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div></br>
    <a asp-controller="Home" asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasBufete/Views/Clientes/Logout.cshtml
@model CitasBufete.Models.Cliente

@{
    ViewData["Title"] = "Cerrar sesión";
}

<h1>Cerrar sesión</h1></br>
<div>
    <h4>Usuario: @Context.Session.GetString("Nombre_cliente")</h4>
    <hr /></br>
    <h3>Desea salir del gestor de citas ?</h3></br>
    <form asp-action="Logout">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Aceptar" class="btn btn-danger" /></br></br>
        <a asp-controller="Clientes" asp-action="CitasCliente">Regresar</a>
    </form>
</div>